spring:
  datasource:
    url: jdbc:mysql:///blog?serverTimezone=UTC
    username: root
    password: 123456


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.donald: debug
  file:
    name: log/blog-dev.log
